ROS 2 add multiple topics
ika-rwth-aachen/mqtt_client pull request #30
Opened 2023-09-06 22:09 UTC by dmbuck32

## Add support for bridging multiple ROS2 topics in a single client

This pull request adds support for bridging multiple MQTT <-> ROS topics in a single client instance. 

This follows the suggestion from this ROS discourse post:
- https://discourse.ros.org/t/use-ros-message-in-parameter-interface/31269/4

2023-09-11 06:03 UTC, lreiher requested changes
Thank you very much for your PR!

I have made some minor suggestions and would be very happy to merge afterwards! :)

Will also try to get to your other PR as soon as possible.

2023-09-11 06:03 UTC, lreiher commented on mqtt_client/src/MqttClient.ros2.cpp
> +  for (auto topic_name : mqtt2ros_topic_names)
```suggestion
  const auto mqtt2ros_topic_names = declare_parameter<std::vector<std::string>>("bridge.mqtt2ros.topics", std::vector<std::string>(), param_desc);
  for (const auto& topic_name : mqtt2ros_topic_names)
```

2023-09-11 06:03 UTC, lreiher commented on mqtt_client/src/MqttClient.ros2.cpp
> +        get_parameter(fmt::format("bridge.ros2mqtt.{}.mqtt_topic", topic_name), mqtt_topic_param)) {
```suggestion
  for (const auto& topic_name : ros2mqtt_topic_names) {
  
    rclcpp::Parameter ros_topic_param, mqtt_topic_param;
    if (get_parameter(fmt::format("bridge.ros2mqtt.{}.ros_topic", topic_name), ros_topic_param) &&
        get_parameter(fmt::format("bridge.ros2mqtt.{}.mqtt_topic", topic_name), mqtt_topic_param)) {
```

2023-09-11 10:23 UTC, lreiher commented
Could you please also modify the GitHub actions `.github/workflows` such that the checks also run on PRs? Apparently we have set it up incorrectly, as no checks are currently being tested in this PR.

Simply change the `on` key to this:
```yml
on: [push, pull_request]
```

2023-09-12 21:21 UTC, dmbuck32 commented on README.md
> +      mqtt_topic:          # MQTT topic on which the corresponding ROS messages are sent to the broker
`topic_name` is a placeholder for the name of the topic being bridged between MQTT & ROS.

The idea being that this `topic_name` identifies the bridge between the ROS & MQTT.

In the ping-pong example:

```yaml
ros2mqtt:            
    topics:              
      - ping
      - ping_primative
    ping:
      ros_topic: /ping/ros
      mqtt_topic: pingpong/ros
    ping_primative:
      ros_topic: /ping/primitive
      mqtt_topic: pingpong/primitive
```

Are you suggesting that we do the following?

```yaml
ros2mqtt:            
    topics:              
      - /ping/ros
      - pingpong/ros
    /ping/ros:
      ros_topic: /ping/ros
      mqtt_topic: pingpong/ros
    pingpong/ros:
      ros_topic: /ping/primitive
      mqtt_topic: pingpong/primitive
```
If so, is `/ping/ros` a valid YAML name?

Alternatively, should the documentation be updated to indicate that this is a placeholder?

```yaml
bridge:
  ros2mqtt:            # Object specifying which ROS topics to map to which MQTT topics
    topics:              # Array specifying which ROS topics to bridge
      - {{ topic_name }}         # The topic that should be bridged, corresponds to the sub-object in the YAML
    {{ topic_name }}:
      ros_topic:           # ROS topic whose messages are transformed to MQTT messages
      mqtt_topic:          # MQTT topic on which the corresponding ROS messages are sent to the broker
```

2023-09-13 07:05 UTC, lreiher commented on README.md
> +      mqtt_topic:          # MQTT topic on which the corresponding ROS messages are sent to the broker
I was suggesting the following. Note that we are only specifying the ros topic information once for each topic this way.

```yml
ros2mqtt:            
    ros_topics:              
      - /ping/ros
      - pingpong/ros
    /ping/ros:
      mqtt_topic: pingpong/ros
    pingpong/ros:
      mqtt_topic: pingpong/primitive
```

I am not 100% sure that this is valid yamland correctly parsed by ROS, but a standard online yaml parser I have just quickly tested didn't complain.

2023-09-15 03:44 UTC, dmbuck32 commented on README.md
> +      mqtt_topic:          # MQTT topic on which the corresponding ROS messages are sent to the broker
Ok, I'll have a look at it this weekend and see if I can get this to work.

2023-09-15 08:01 UTC, lreiher commented on README.md
> +      mqtt_topic:          # MQTT topic on which the corresponding ROS messages are sent to the broker
Great, thanks a lot! After this PR is merged as well, I will go ahead and make another release.

2023-09-17 04:34 UTC, dmbuck32 commented on README.md
> +      mqtt_topic:          # MQTT topic on which the corresponding ROS messages are sent to the broker
I was able to get this working, apparently it is possible to have a forward slash in a ROS parameter path.

2023-09-18 06:01 UTC, lreiher approved these changes
Great, thanks a lot!

2023-09-18 06:01 UTC, merged